site_name: Artist's Notebook
site_url: http://notes.artistuniverse.tech

theme: 
  name: material
# custom_dir: overrides
  favicon: images/favicon.png
  language: en
  icon:
  logo: images/favicon.png
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.path
#    - navigation.expand
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  plugins:
    - typeset
    - search
    - mkdocs-pdf
#    - pub-obsidian:
#      obsidian_dir: .obsidian

  palette:

    # Palette toggle for dark mode
    - scheme: default
      primary: deep purple
      accent: yellow
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for light mode
    - scheme: slate
      primary: deep purple
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

# if you want to be able to use emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# table of contents with permalink
  - toc:
      permalink: true

# make custom admonitions
extra_css:
  - stylesheets/extra.css

extra:
  generator: true
  social:
    - icon: simple/youtube
      link: https://www.youtube.com/@ArtistUniverseUntouched

# add images to files like so ![screenshot](../assets/GitHub_Issue.png)
nav:
  - Home: index.md
  - Identity & Access Management:
    - Overview: identity_and_access_management/fundamentals/Overview.md
    - Authentication vs Authorization:  identity_and_access_management/fundamentals/authentication_vs_authorization.md
    - Identity vs Account vs Principal: identity_and_access_management/fundamentals/identity_vs_account_vs_principal.md
    - Claims. Tokens. Sessions: identity_and_access_management/fundamentals/claims_tokens_sessions.md
    - Federation. Trust relationships: identity_and_access_management/fundamentals/federation_and_trust_relationships.md
    - Open Standards:
      - OAuth 2.0: identity_and_access_management/fundamentals/open_standards/oauth_2.0.md
      - OpenID Connect: identity_and_access_management/fundamentals/open_standards/openid_connect.md
      - SAML 2.0: identity_and_access_management/fundamentals/open_standards/saml.md
      - SCIM: identity_and_access_management/fundamentals/open_standards/scim.md